import React,{useState} from "react";
let words = `letter morning until water deep real boy little hot last any land that came idea than usual first they are warm island stay remember feet thing mother feel earth answer heard city change quick dry now other our green open done her up fly red let men or above under began voice sentence cry those five old sure well week while strong minute ship many ready four large way know science wind notice both often night if multiply fish fine differ paper take hand about right love test watch care correct better direct learn has consider high like three wait out equate clear piece example part might hear great what see through more center full point carry kind year class snow surface pound white state told name an hundred serve possible found with get foot wood side study stood two add family home sound cross every ago play problem have stop brought ever best king look east adventure order slow how though front cause air must sing distant them this page fill but us free inch some lead place numeral never need enough door next stand world language ask it body also paint map field can hot word before put cat special base ten mean was own music self fact were time grand call urge pull west set house thought each verb spell war machine true one soon country top together there century ease simple plant here person went miss took figure find close day mile ball car turn who dog does among room list heat gold far moon step his pose my back half decide would tree ocean product school farm keep food move appear children rock use live over rain after line wheel tire had think area rule again town end lay song since same still come short once your of note certain may do give show course go seem most follow leave interest grow number help main could fall young pattern animal during all picture girl on people off life street power beauty book walk star blue got boat dark round eye hard should box develop early write near him contain story head begin common teach hold said six when question whole long govern measure ground their produce able small mind plane very sun to several which make face want north mountain noun the late table behind plain say in he no cut you run low black stead south between second check is where try wonder will plan by yet record game good rest less father listen wave cover much port saw few why laugh act sea she been even just toward system final press shape hour talk cold then read fire and travel bring only left space draw light me drive tail tell such so man reach form for river unit happen complete thousand vowel always down big new these force nothing against horse pass eat start ran work busy object too color yes gave money did we build knew made`;
export default function randomWords<T extends number>(limit:T){
    const arrOfWords = words.split(' ');
    let out = [];
    for(let i = 0;i<limit;i++){
        out.push(arrOfWords[Math.floor(Math.random()*arrOfWords.length)])
    }
    return out.join(' ')
}